---  # Apache Jena & Fuseki triple store
version: '3'
services:
  graphdb:
    image: khaller/graphdb-free
    container_name: graphdb
    volumes:
      - $HOME/CWTS/Apps/graphdb/databases:/opt/graphdb/data/repositories
    ports:
      - 7200:7200
  flask:
    build:
      context: .
      dockerfile: ./flask/Dockerfile
    container_name: flask
    environment:
      - APP_ENVIRONMENT=develop
      - APP_HOST=0.0.0.0
      - APP_PORT=5001
      - APP_SPARQL_QUERY_ENDPOINT=http://graphdb:7200/repositories/job
      - APP_SPARQL_UPDATE_ENDPOINT=http://graphdb:7200/repositories/job/statements
    ports:
      - 5001:5001
