---  # Apache Jena & Fuseki triple store
version: '3'
services:
  fuseki:
    user: root
    image: fuseki
    build: ./jena
    container_name: fuseki
    volumes:
      - $HOME/CWTS/data:/data
      - $HOME/CWTS/Apps/fuseki/databases:/fuseki/databases
      - $HOME/CWTS/Apps/fuseki/configuration:/fuseki/configuration
    ports:
      - 3030:3030
