# Provenance
insert {
    graph sub:docinfo {
        this: a pad:PAD ;
            pad:hasProvenance sub:provenance ;
            pad:hasAssertion sub:assertion ;
            pad:hasDocInfo sub:docinfo .
        sub:provenance a pad:Provenance .
        sub:assertion a pad:Assertion .
        sub:docinfo a pad:DocInfo .
    }

    graph sub:provenance {
        sub:assertion dcterms:license <https://creativecommons.org/publicdomain/zero/1.0/> ;
            dcterms:created ?date ;
            dcterms:creator <https://doaj.org> .
    }
}
where {
    ?journal a rdfg:Graph .
    ?journal schema:dateModified ?date .
}

# Metadata
insert {
    graph sub:assertion {
        ?journal a ppo:Platform ;
            schema:name ?journal_title ;
            ppo:hasKeyword ?keyword .
    }
}
where {
    ?journal a rdfg:Graph .
    ?journal schema:name ?journal_title .
    optional { ?journal doaj:keyword ?keyword . } 
}

# Identifier
insert {
    graph sub:assertion {
        ?journal ?hasissn ?issn .
    }
}
where {
    ?journal a rdfg:Graph .
    ?journal ?hasissn ?issn . 
    filter ( ?hasissn in (prism:issn, prism:eIssn) ) .
}

# Organization
insert {
    graph sub:assertion {
        ?journal dcterms:publisher ?publisher .

        ?publisher a pro:publisher ; 
            schema:name ?publisher_name ;
            schema:addressCountry ?publisher_country ;
            schema:url ?publisher_url .
    }
}
where {
    ?journal a rdfg:Graph .
    ?journal doaj:Publisher ?publisher .
    optional { ?publisher schema:addressCountry ?publisher_country } .
    optional { ?publisher schema:url ?publisher_url } .
    optional { ?publisher schema:name ?publisher_name } .
}

# Publication Policy
insert {
    graph sub:assertion {
        ?journal ppo:hasPolicy sub:publicationPolicy .
        sub:publicationPolicy a ppo:PublicationPolicy ;
            ppo:isOpenAccess true ;
            ppo:hasArticlePublishingCharges ?apc ;
            ppo:hasCopyrightOwner ?copyright_owner ;
            dcterms:license ?license ;
            ppo:appliesToVersion pso:published .
        
        ?apc a ppo:ArticlePublishingCharges ;
            schema:url ?apc_url ;
            schema:price ?apc_price ;
            ?apc_p ?apc_o .

        ?copyright_owner a ?copyright_owner_type .
    }
}
where {
    ?journal a rdfg:Graph .

    optional { ?journal ppo:hasArticlePublishingCharges ?apc } .
    optional { ?apc schema:PriceSpecification [ ?apc_p ?apc_o ] } .
    optional { ?apc schema:url ?apc_url } .
    optional { ?apc doaj:ArticlePublishingChargesApply false . bind(0 as ?apc_price) } .

    optional {
        ?journal doaj:Copyright ?oa_copyright .
        ?oa_copyright doaj:authorRetainsCopyright ?copyright_author_p .
        bind(sub:author as ?author)
        optional { ?journal doaj:Publisher ?publisher . }
        bind(if(bound(?publisher), ?publisher, sub:publisher) as ?publisher)
        bind(if(?copyright_author_p=true, ?author, ?publisher) as ?copyright_owner) .
        bind(if(?copyright_author_p=true, pro:author, pro:publisher) as ?copyright_owner_type) .
    }
    
    optional {
        ?oa_license doaj:licenseType ?license_type .
        optional {
            ?oa_license schema:url ?license_url .
            bind(IRI(?license_url) as ?license_iri) .
        }
        bind(if(?license_type = "CC0", IRI("https://creativecommons.org/publicdomain/zero/1.0/"), ?_) as ?cc_license)
        bind(if(?license_type = "CC BY", IRI("https://creativecommons.org/licenses/by/4.0/"), ?_) as ?cc_license)
        bind(if(?license_type = "CC BY-NC", IRI("https://creativecommons.org/licenses/by-nc/4.0/"), ?_) as ?cc_license)
        bind(if(?license_type = "CC BY-NC-ND", IRI("https://creativecommons.org/licenses/by-nc-nd/4.0/"), ?_) as ?cc_license)
        bind(if(?license_type = "CC BY-NC-SA", IRI("https://creativecommons.org/licenses/by-nc-sa/4.0/"), ?_) as ?cc_license)
        bind(if(?license_type = "CC BY-ND", IRI("https://creativecommons.org/licenses/by-nd/4.0/"), ?_) as ?cc_license)
        bind(if(?license_type = "CC BY-SA", IRI("https://creativecommons.org/licenses/by-sa/4.0/"), ?_) as ?cc_license)
        bind(coalesce(?license_iri, ?cc_license) as ?license)
    } .
}
